import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import MainMenu from "@/components/menu/MainMenu";
// import StoreProvider from "@/redux/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EZPay4U",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("layout");
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          {children}
          <MainMenu />
        </StoreProvider>
      </body>
    </html>
  );
}
